name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform - ${{ matrix.environment }}

    # Manual execution is allowed only from main.
    if: ${{ github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main' }}

    strategy:
      fail-fast: false

      matrix:
        environment: ${{ fromJSON(
          github.event_name == 'workflow_dispatch'
          && format('["{0}"]', inputs.environment)
          || '["dev","qa","prod"]'
          ) }}

    uses: ./.github/workflows/terraform-environment.yml

    with:
      environment: ${{ matrix.environment }}
      directory: infra/${{ matrix.environment }}
      workspace: nextech-${{ matrix.environment }}

      # PR = validate + plan only
      # push/main or manual = validate + plan + apply
      apply: ${{ github.event_name != 'pull_request' }}

    secrets: inherit
