name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: Environment to apply
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  contents: read


jobs:

  # PR:
  # run dev / qa / prod independently
  # validate -> plan
  terraform-plan:
    name: Terraform Plan - ${{ matrix.environment }}

    if: github.event_name == 'pull_request'

    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - qa
          - prod

    concurrency:
      group: terraform-${{ matrix.environment }}-${{ github.ref }}
      cancel-in-progress: true

    uses: ./.github/workflows/terraform.yml

    with:
      environment: ${{ matrix.environment }}
      working-directory: infra/${{ matrix.environment }}
      workspace: nextech-${{ matrix.environment }}
      apply: false

    secrets: inherit


  # Push to main:
  #   dev / qa / prod
  #
  # Manual:
  #   only selected environment
  terraform-apply:
    name: Terraform Apply - ${{ matrix.environment }}

    if: >
      github.event_name == 'push' ||
      (
        github.event_name == 'workflow_dispatch' &&
        github.ref == 'refs/heads/main'
      )

    strategy:
      fail-fast: false
      matrix:
        environment: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', inputs.environment)) || fromJSON('["dev","qa","prod"]') }}

    concurrency:
      group: terraform-${{ matrix.environment }}
      cancel-in-progress: false

    uses: ./.github/workflows/terraform.yml

    with:
      environment: ${{ matrix.environment }}
      working-directory: infra/${{ matrix.environment }}
      workspace: nextech-${{ matrix.environment }}
      apply: true

    secrets: inherit
